description = "Platform agnostic drivers to interface external components"
long-description = '''# embedded-components

Platform agnostic drivers to interface external components.

This crate is a snapshot of the `components` of [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/components).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''

name = "embedded_components"
version = "0.1.0"
licenses = ["BSD 3-Clauses"]
authors=["AdaCore"]
website="https://github.com/AdaCore/Ada_Drivers_Library/"
maintainers = ["chouteau@adacore.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["embedded_components.gpr"]
tags = ["embedded", "nostd"]

[[depends-on]]
hal = "^0.1.0"
adl_middleware = "^0.1.1"
